app_name: gpii-webdriver

git_repository: https://github.com/the-t-in-rtf/gpii-webdriver.git

email: tony@raisingthefloor.org

env_runtime: linux-desktop

app_start_service: false

software_stack: nodejs

software_stack_version: 4.3.1

setup:
  - sudo dnf -y install java-1.8.0-openjdk-devel.x86_64
  - sudo npm install -g webdriver-manager
  - sudo webdriver-manager --chrome
  - npm install

commands:
  - npm test