# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
app_name: gpii-webdriver

git_repository: https://github.com/the-t-in-rtf/gpii-webdriver.git

email: tony@raisingthefloor.org

env_runtime: linux-desktop

app_start_service: false

software_stack: nodejs

software_stack_version: 4.3.1

setup:
  - sudo dnf -y install java-1.8.0-openjdk-devel.x86_64
  - npm install

commands:
  - export PATH=$PATH:/home/vagrant/sync/node_modules/chromedriver/bin/chromedriver/
  - xhost +
  - export DISPLAY=:0
  - BROWSERS=chrome npm test