# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure

email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-webdriver
    app_start_service: false
    git_repository: https://github.com/the-t-in-rtf/gpii-webdriver.git
    git_branch: GPII-1913
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-express
    run_in: fedora
    deploy: false
    setup:
      - sudo dnf -y install java-1.8.0-openjdk-devel.x86_64
      - yarn install
    test_cmds:
      - PATH=$PATH:/home/vagrant/sync/node_modules/chromedriver/bin/chromedriver/ BROWSERS=chrome yarn test
